<<<<<<< HEAD
version: "3"

services:
  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
    

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
=======
version: "3"

services:

  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
    networks:
      - app-network
    

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"
    networks:
      - app-network

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - app-network

volumes:
  ckan_storage:
  pg_data:
  solr_data:

#Docker Networks
networks:
  app-network:
    driver: bridge
>>>>>>> 281030e (nginx for prod)
